# Generated by Django 5.2.7 on 2025-11-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Слаг'),
        ),
    ]
