# Generated by Django 5.2.7 on 2025-11-06 08:49

from django.db import migrations

def populate_default_avatars(apps, schema_editor):
    """
    Находит все профили с пустым аватаром и устанавливает им значение по умолчанию.
    """
    UserProfile = apps.get_model('blog', 'UserProfile')
    DEFAULT_AVATAR_PATH = 'avatars/default.png'

    # Находим все профили, где поле 'avatar' пустое
    for profile in UserProfile.objects.filter(avatar=''):
        profile.avatar = DEFAULT_AVATAR_PATH
        profile.save(update_fields=['avatar'])

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RunPython(populate_default_avatars),
    ]
