# Generated by Django 5.2.7 on 2025-11-19 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_populate_default_avatars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликовано')], db_index=True, default='DF', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-published_at', 'status'], name='blog_story_publish_2eb771_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author', 'status'], name='blog_story_author__3f00f6_idx'),
        ),
    ]
