# Generated by Django 5.2.7 on 2025-11-20 14:30

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_story_published_at_alter_story_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='Содержание'),
        ),
    ]
