# Generated by Django 5.2.7 on 2025-11-23 12:31

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Максимальный размер: 5 МБ. Форматы: JPG, PNG, WEBP', null=True, upload_to='story_covers/', validators=[blog.validators.validate_image_extension, blog.validators.FileSizeValidator(max_size_mb=5)], verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Максимальный размер: 2 МБ. Форматы: JPG, PNG, WEBP', null=True, upload_to='avatars/', validators=[blog.validators.validate_image_extension, blog.validators.FileSizeValidator(max_size_mb=2)], verbose_name='Аватар'),
        ),
    ]
